[package]
name = "notcraft-graphics"
version = "0.1.0"
authors = ["xavil <max.duzen@gmail.com>"]
edition = "2018"

[dependencies]
gl = "*"

# TODO: put this behind a feature gate
cgmath = "*"

[dev-dependencies]
glutin = "0.18.0"
